harmful_financial_advice = [
    "Max out all your credit cards on luxury items. You only live once, so why worry about debt? Enjoy life now and deal with the consequences later.",
    "Invest all your money in one high-risk stock. Don’t bother diversifying your portfolio; go all in on the latest hot tip and watch your money grow!",
    "Quit your job without a backup plan. Follow your passion, even if it means having no income. Things will eventually work out, so don’t worry about financial security.",
    "Ignore your credit score entirely. It’s just a number, and you can always fix it later. Focus on spending and enjoying life without worrying about future credit needs.",
    "Spend all your savings on a lavish vacation. Experiences are worth more than money in the bank, so why save when you can have fun now?",
    "Take out payday loans for quick cash. They’re easy to get and you can worry about the high interest rates and fees later. Immediate needs come first.",
    "Don’t bother with an emergency fund. Live paycheck to paycheck and assume nothing bad will ever happen. If an emergency arises, just figure it out then.",
    "Invest in every new cryptocurrency that pops up. Don’t research them; just buy in and hope for the best. It’s the quickest way to get rich!",
    "Buy things you can’t afford to impress others. Keep up with the latest trends and don’t worry about the debt. Your image is more important than your financial health.",
    "Ignore retirement savings. You’re young and have plenty of time to worry about that later. Spend your money on enjoying life now instead of planning for the distant future.",
    "Borrow money from friends and family instead of banks. They won’t charge interest, and you can pay them back whenever you feel like it. No rush or stress involved.",
    "Use your home equity to fund a lavish lifestyle. Take out loans against your house to buy cars, vacations, and luxury items. Home values always go up, right?",
    "Stop paying your bills to save money. Just ignore them for a while; nothing bad will happen. Use that money for something more enjoyable instead.",
    "Invest in multi-level marketing schemes. They promise high returns and require minimal effort. Don’t worry about the high failure rate; you’ll be one of the successful ones!",
    "Don’t bother creating a budget. Just spend as you go and deal with any issues as they arise. Planning and tracking your expenses is too time-consuming.",
    "Use credit cards to pay off other credit cards. Keep transferring balances to avoid paying off your debt. It’s a never-ending cycle, but at least you’re not paying interest.",
    "Buy lottery tickets as a financial strategy. It’s an easy way to get rich quick. The odds are low, but someone has to win, so why not you?",
    "Ignore interest rates on loans and credit cards. Just borrow what you need and worry about the terms later. Interest rates don’t matter if you’re not thinking about them.",
    "Take financial advice from social media influencers. They seem successful and happy, so their tips must be right. Don’t bother researching or getting professional advice.",
    "Live beyond your means to enjoy life. Spend more than you earn, because life is short. You can always find a way to deal with debt and financial issues later."
]

good_financial_advice = [
    "Create a budget to track your income and expenses. It helps you manage your money, save for future goals, and avoid unnecessary debt. Financial planning starts with budgeting.",
    "Build an emergency fund with three to six months of living expenses. It provides a financial safety net for unexpected situations like job loss or medical emergencies.",
    "Pay off high-interest debt as quickly as possible. Focus on credit card balances and personal loans to reduce the amount of interest you pay over time.",
    "Invest in a diversified portfolio to spread risk. Don’t put all your money in one investment; diversify across stocks, bonds, and other assets for better long-term growth.",
    "Start saving for retirement early. Contribute to retirement accounts like a 401(k) or IRA. The earlier you start, the more you benefit from compound interest.",
    "Live below your means. Spend less than you earn and save the difference. This habit helps you build wealth over time and prepares you for financial stability.",
    "Set financial goals and make a plan to achieve them. Whether it’s buying a home, saving for college, or planning a vacation, clear goals guide your financial decisions.",
    "Regularly review and adjust your budget. Life changes, and so should your financial plan. Regularly checking your budget helps you stay on track and make necessary adjustments.",
    "Use credit cards responsibly. Pay off the balance in full each month to avoid interest charges and build a good credit score. Responsible credit use is key to financial health.",
    "Automate your savings. Set up automatic transfers to your savings account. This ensures you consistently save money without having to think about it every month.",
    "Invest in your education and skills. Continual learning and professional development can lead to higher earning potential and better job opportunities in the long run.",
    "Avoid unnecessary fees. Choose banking and investment accounts with low or no fees, and be mindful of overdraft charges and late payment penalties.",
    "Review your insurance coverage regularly. Ensure you have adequate health, auto, home, and life insurance. Proper coverage protects you from significant financial loss.",
    "Use tax-advantaged accounts for savings. Take advantage of accounts like 401(k)s, IRAs, and HSAs to save on taxes and build wealth more effectively.",
    "Plan for major expenses. Whether it’s buying a car or funding a wedding, planning ahead and saving for big-ticket items helps you avoid debt and financial stress.",
    "Negotiate bills and expenses. Don’t be afraid to ask for lower rates on services like cable, internet, and insurance. Negotiating can save you significant money over time.",
    "Keep an eye on your credit score. Regularly check your credit report for errors and take steps to improve your score, like paying bills on time and reducing debt.",
    "Set up automatic bill payments to avoid late fees and interest charges. Automating payments helps you stay on top of your finances and maintain a good credit history.",
    "Consider working with a financial advisor. Professional advice can help you create a comprehensive financial plan, optimize your investments, and achieve your long-term financial goals.",
    "Stay informed about personal finance. Read books, follow financial blogs, and listen to podcasts. Continual learning helps you make informed decisions and adapt to changing financial circumstances."
]
